### ISSUE TITLE
[Design] Text Overflow

### ISSUE THREAD

**Issue by Akshu-on-github** [CrazyChickenDev/MyPortfolio#5]
Hi there!
I happened to come across your portfolio site - It's pretty cool! I loved the opening animations and the navbar, but I did notice this one little thing:

![image](https://user-images.githubusercontent.com/61582763/102377621-e746b500-3fea-11eb-83a3-4cfd87ae1682.png)

The text isn't contained within the box. Not a huge distraction, but I thought I'd let you know anyways!

**Comment by CrazyChickenDev** [comment]
Thanks, I'll sort that out
